version: "3"

services: 
    express-server:
        build: .
        image: homepage
        restart: unless-stopped
        ports: 
            - "127.0.0.1:3000:3000"
        networks: 
            - homepage-app
        depends_on: 
            - mongo
    mongo:
        image: mongo
        restart: unless-stopped
        networks: 
            - homepage-app
        volumes: 
            - mongo-data:/data/db

networks: 
    homepage-app:
        driver: bridge

volumes: 
    mongo-data:
        driver: local
